"""Generate deterministic Python namespaces for catalog datasets."""

import re
from collections import defaultdict
from pathlib import Path

from etlonomy.catalog import SQLiteCatalog
from etlonomy.exceptions import CatalogError


def _identifier(value: str) -> str:
    identifier = re.sub(r'\W', '_', value).upper()
    if not identifier.isidentifier():
        identifier = f'_{identifier}'
    return identifier


def _class_name(subject: str) -> str:
    return f'_{_identifier(subject).title()}'


def generate_datasets(catalog: SQLiteCatalog, output: Path) -> None:
    """Write deterministic dataset constants from a SQLite catalog."""
    grouped: dict[str, list[str]] = defaultdict(list)
    collisions: dict[tuple[str, str], str] = {}
    class_names: dict[str, str] = {}
    for dataset in catalog.list_datasets():
        subject_name = _identifier(dataset.subject)
        dataset_name = _identifier(dataset.name)
        key = (subject_name, dataset_name)
        canonical_name = str(dataset)
        if key in collisions and collisions[key] != canonical_name:
            raise CatalogError(
                f'datasets {collisions[key]} and {canonical_name} have the same Python name'
            )
        collisions[key] = canonical_name
        class_name = _class_name(dataset.subject)
        previous_subject = class_names.get(class_name)
        if previous_subject is not None and previous_subject != dataset.subject:
            raise CatalogError(
                f'subjects {previous_subject} and {dataset.subject} have the same '
                'generated Python class name'
            )
        class_names[class_name] = dataset.subject
        grouped[dataset.subject].append(dataset.name)

    lines = [
        '"""Generated by ETLonomy; do not edit manually."""',
        '',
        'from etlonomy import DatasetId',
        '',
    ]
    for subject in sorted(grouped):
        class_name = _class_name(subject)
        lines.append(f'class {class_name}:')
        lines.append(f'    """Datasets in the {subject} subject area."""')
        for name in sorted(grouped[subject]):
            lines.append(f"    {_identifier(name)} = DatasetId('{subject}', '{name}')")
        lines.append('')
    lines.extend(['class Datasets:', '    """Generated logical dataset namespace."""'])
    if not grouped:
        lines.append('    pass')
    for subject in sorted(grouped):
        class_name = _class_name(subject)
        lines.append(f'    {_identifier(subject)} = {class_name}()')
    source = '\n'.join(lines) + '\n'
    try:
        compile(source, str(output), 'exec')
    except SyntaxError as error:
        raise CatalogError(f'generated dataset module is invalid: {error}') from error
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding='utf8')
